### Anlegen
POST http://127.0.0.1:8080/api/books
Content-Type: application/json

{
  "title": "Clean Code",
  "author": "Robert C. Martin"
}

###
GET http://127.0.0.1:8080/api/books

###
GET http://127.0.0.1:8080/api/books/1

###
DELETE http://127.0.0.1:8080/api/books/1

###
GET http://127.0.0.1:8080/api/books/999
